{{- if .Values.paybox.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-paybox-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  PAYBOX_TRYTON_USERNAME: {{ .Values.paybox.coog_username | quote }}
  PAYBOX_TRYTON_PASSWORD: {{ .Values.paybox.coog_password | quote }}
{{- end }}