dependencies:
- name: mongodb
  version: 7.14.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled

- name: redis
  version: 10.5.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled

- name: postgresql
  version: 8.9.6
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled

- name: flower
  version: 0.1.5
  repository: https://raw.githubusercontent.com/coopengo/coog-helm-charts/master
  condition: flower.enabled

  #- name: nginx
  #version: 5.1.6
  #repository: https://charts.bitnami.com/bitnami
  #condition: nginx.enabled
